### ISSUE TITLE
Viewport.SetClearColor does not work

### ISSUE THREAD

**Issue by bayganik** [Urho-Net/Urho.Net#15]
var render = Renderer;
            Viewport vp = new Viewport(Context, scene, camera, null);
            vp.SetClearColor(Color.Yellow);
            render.SetViewport(0, vp);

The background is always black.  Am I doing something wrong?

**Comment by elix22** [comment]
Well , this specific one doesn't work either on  Urho3D native vanilla .

The simplest  way to implement it is :

```
var zone = scene.CreateComponent<Zone> ();
zone.FogColor = Color.Yellow;
```

Or if you already have a Zone component in your scene 

`scene.GetComponent<Zone>().FogColor = Color.Yellow;`

**Comment by elix22** [comment]
Well ,
I Had now some time to look at the implementation
My bad , this is a pure C# implementation .
Looks like a bug .
For now you can use my proposal , till I fix it

**Comment by bayganik** [comment]
Ah !!! It works in UrhoSharp, so I thought may be you may have the same code base.

**Comment by elix22** [comment]
Not exactly .
I started with the same codebase but since then it deviated substantially .
- Zero dependency on Xamarin , runs directly on top of the Mono/Dotnet runtime (Mobile/Desktop)
- Based on the latest Urho3D vanilla.
- Metal support on iOS
- New features
Literally more than ~650 new commits.

All these goodies actually introduced some new bugs , such as this one :)
Will be fixed in the next binaries release

**Comment by bayganik** [comment]
Thank you for keeping this library updated.  I've really enjoyed how fast this is.

Keep on truckin ...

**Comment by elix22** [comment]
Fixed on the latest Main branch
